Portfolio: mobile menu
tGemechis7/Portfolio pull request #17
Opened 2023-03-13 21:10 UTC by tGemechis7

> I add JavaScript to make hamburger active 
> Modify index.html to accept JavaScript
>added JavaScript to display  Mobile Menu
> I added responsive menu

2023-03-13 21:50 UTC, Munsa1 requested changes
Hi @tGemechis7, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Illustrated Knowledge of JavaScript :heavy_check_mark: 
Followed give Figma Template :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._
- [ ] Kindly use the imperative tense for all your commit messages going forward and please capitalize the first letter of the first word in each commit message as this is the best practice. Read the following article for more [information](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)

- [ ] KIndly set up your linters correctly. This is the first time you have to set up JavaScript, HTML, and CSS linters. Please ensure that `ESLINT` linter checks are present and passing on your PR
![image](https://user-images.githubusercontent.com/81932478/224840755-7318a5a6-922e-4c4f-8ba0-81c1dad884b6.png)



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-13 21:50 UTC, Munsa1 commented on index.html
> +    <!-- <header>
- [ ] Its good practice to remove all unecessary commented code as this makes your codebase more readable to other collaborators. Kindly remove line 16 to 28( the commented code).

2023-03-13 21:50 UTC, Munsa1 commented on index.html
> +        </ul>
- [ ] Clicking on each of these links should close the mobile menu and take the user to the selected part of the page. For example, if the user clicks on the `Portfolio` link, the mobile menu should close and take the user to the `projects` part of the page. The same should happen when the `About` and `Contact` links are clicked, the user should be directed to the `about` and `contact` sections of the page respectively. Kindly implement this requirement.

![image](https://user-images.githubusercontent.com/81932478/224838984-6645423e-1463-4baa-ba8d-bd4802ca5b0b.png)

2023-03-13 21:50 UTC, Munsa1 commented on index.html
> +        </div>
- [ ] There is an overflow on the mobile menu which is causing it to no be displayed properly. Kindly fix it.
![image](https://user-images.githubusercontent.com/81932478/224839819-9f3b96aa-47f0-40bc-b1af-516f0a1b4a65.png)

Given design
![image](https://user-images.githubusercontent.com/81932478/224839970-b9c85e84-88e0-4406-98e0-0bb405e2cea0.png)

2023-03-14 09:19 UTC, OyePriscilla requested changes
Hi @tGemechis7 👏 , 

Great work on making the changes requested by a previous reviewer 👏 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Implemented mobile menu ✔️ 
Used JavaScript event listener ✔️  

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [optional] Please kindly update your README file with the future feature header, it is part of the requirement but missed by last CR. ℹ️  

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-14 09:19 UTC, OyePriscilla commented on index.html
> +            </li>
- [ ] It's awesome adding  a link to the **portfolio section** as raised earlier, but when I click on the portfolio, I was redirected to your header section. Perhaps you may need to remove the **id** given to the main element in **line 39** and add it to **line 93** where we have the portfolio section. 👍

2023-03-14 09:19 UTC, OyePriscilla commented on index.html
> +    <script src="javascript.js"></script>
- [ ] Please, kindly add the **eslint** linter as suggested earlier. This **linter** will help you to find and fix problems with your JavaScript code. Kindly reference this [link](https://github.com/microverseinc/linters-config/tree/master/html-css-js)   for more information on how to set it up. ℹ️

2023-03-14 11:04 UTC, tGemechis7 commented on index.html
> +    <script src="javascript.js"></script>
hello @OyePriscilla Can you please check once again I tried solve your comment

2023-03-14 11:48 UTC, OyePriscilla commented on index.html
> +    <script src="javascript.js"></script>
@tGemechis7 Awesome! the eslint linter is not yet added. Kindly go through [link](https://github.com/microverseinc/linters-config/tree/master/html-css-js) in order to set it up.

2023-03-14 12:25 UTC, tGemechis7 commented on index.html
> +    <script src="javascript.js"></script>
Hello @OyePriscilla I tried to configure the eslint in the linter file and i noticed the eslint is working perfectly and passing but to my surprise i notice the lighthouse keeps failing and i have tried all my possible best to resolve it but all attempt seems not to be working

2023-03-14 12:32 UTC, OyePriscilla commented on index.html
> +    <script src="javascript.js"></script>
@tGemechis7 try and change the node version for lighthouse from 18.x to 12.x in linters.yml file

2023-03-14 12:45 UTC, tGemechis7 commented on index.html
> +    <script src="javascript.js"></script>
Hello @OyePriscilla thank you it passed now

2023-03-14 13:16 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle: :1st_place_medal: :100:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)

### Hey @tGemechis7, @GhostEsso 👋

Great work on implementing the requested changes. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Requirements
:heavy_check_mark: Following GitHub Flow

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-14 13:16 UTC, HAMMAS-SALEEM commented on README.md
![image](https://user-images.githubusercontent.com/93039359/225010905-61ea372a-a5a4-4533-b882-0737fb3d638f.png)

**[Optional]**

- [ ] It would be nice if you make all your commit messages meaningful and capitalize to make your pull request professional :blush:

2023-03-14 13:16 UTC, HAMMAS-SALEEM commented on README.md
## 1.
![image](https://user-images.githubusercontent.com/93039359/225011290-d9412616-dee0-47aa-892d-9294665c323a.png)

## 2.
![image](https://user-images.githubusercontent.com/93039359/225011415-e649c734-5c4b-47ba-a54b-a6ebd0a79fb2.png)

**[Optional]**

- [ ] Kindly remove both of these instructions to make your readme file look clean, professional and descriptive :+1:

2023-03-14 13:16 UTC, HAMMAS-SALEEM commented on README.md
![image](https://user-images.githubusercontent.com/93039359/225011744-f521b79c-68d1-4a06-83cb-e0a1053a1306.png)

**[Optional]**

- [ ] I am not able to figure out what you are trying to say in this section :thinking: Kindly make your message more clear and professional such as **If you like this project then don't forget to give a star :star: on this repository** to make your readme descriptive :+1:

2023-03-14 13:42 UTC, tGemechis7 commented on README.md
Hello@HAMMAS-SALEEM ok thanks  a lot i will improve all your comment

2023-03-14 13:43 UTC, merged

2023-03-14 14:11 UTC, OyePriscilla commented on index.html
> +    <script src="javascript.js"></script>
@tGemechis7 I'm glad to hear this!