Portfolio finish mobile version
tGemechis7/Portfolio pull request #3
Opened 2023-02-17 21:00 UTC by tGemechis7

I have created the work section , About myself and other in this project using HTML, CSS, JavaScript
i have created html part with flexbox, Grid css
this project makes me best software developer as ajunior

2023-02-17 21:49 UTC, vickymarz requested changes
Hi @tGemechis7, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 21:49 UTC, vickymarz commented on index.html
> +    <section id="portfolio" class="project-section">
- [ ] Good job adding the project cards. Kindly note that the project requirement expects that the main container of the projects has a `display:grid`. Therefore use `grid` to align the entire project section. The goal is to get you familiar with `grid` and `flexbox`

2023-02-17 21:49 UTC, vickymarz commented on index.html
> +    <section id="portfolio" class="project-section">
- [ ] Your project section seems to have a horizontal scrollbar which is not a good user experience and it also affects the responsiveness of your webpage. Kindly fix it 👍🏽 

![image](https://user-images.githubusercontent.com/63473584/219796660-97615000-9904-426b-b009-3ad2cc46ab0a.png)

2023-02-17 21:49 UTC, vickymarz commented on main.js
> +      <div class='projects'>
- [ ] Good job aligning your project card with flexbox. Kindly fix the alignment and spacing of the elements of your project cards to match the figma design 👍🏽 

your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/219797342-cf784e9b-21c8-414b-9069-0e21754804de.png)
  
figma design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/219797753-262c4482-5995-41a9-ae88-4543156af0bc.png)

2023-02-17 21:49 UTC, vickymarz commented on index.html
> +    <section id="about" class="about">
- [ ] Kindly ensure that you align the elements of your about section to match the figma design. Make sure you use the right font-weight. font-size and color of the texts of the about section to match the figma design 💯 , 

Your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/219799677-170e2a10-093e-4846-8141-0b2f614412a7.png)

Figma design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/219799804-9e65826e-8af7-4471-8011-164bbda4e705.png)

2023-02-17 21:49 UTC, vickymarz commented on index.html
> +            <ul class="language-list">
- [ ] KIndly add padding around your list of technologies and also reduce the size of the arrows to match the figma design

your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/219800131-ee57da31-63e3-4b96-8f03-bc63caff75eb.png)

figma design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/219800259-2f6359c1-664f-4549-9b14-8b1a2dfb769e.png)

2023-02-18 03:26 UTC, shella12 requested changes
Hi @tGemechis7 , 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. You are almost there...

<img src="https://media0.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

## Highlights

- Fixed horizontal scrolling ✅ 

 ## Required Changes ♻️

- [ ] _Check the comments under the review._

## Optional suggestions

- [ ] [OPTIONAL] Please use descriptive commit messages. The commit message should be written in the imperative tense and capitalized. [Read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8). For instance instead of saying `added javascript to save data` say `Add javascript to save data`.Its one of the requirements of the project but please try to keep this in mind for future


<img width="375" alt="Screenshot 2023-02-18 at 8 16 17 AM" src="https://user-images.githubusercontent.com/44798044/219828881-af2301c3-e2f0-43c8-895f-83a530dfe0c7.png">


- [ ] [OPTIONAL] Great job using the Microverse template for your README and customizing it to reflect your project. 
    - [ ]  [OPTIONAL] Great job adding a link to the MIT Licence into your README, but please remove _`Note:`_ from the LICENCE section of the README. Note is there in the template to guide you on how you to add a LICENCE to your README. Once you have successfully added the LICENCE you can go ahead and remove it


    - [ ] [OPTIONAL] Please remove the default comment like

>             Give credit to everyone who inspired your codebase.  

>            Write a message to encourage readers to support your project  

>             Describe 1 - 3 features you will add to the project.  ,etc from your README. 

They were used in the template to explain to the user the purpose of each section. You can go ahead and remove it from your README.  

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-18 03:26 UTC, shella12 commented on main.js
> +      <div class='projects'>
- [ ]  As request by the previous reviewer Kindly ☺️ fix the alignment and spacing of the elements of your project cards to match the figma design as it is the [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md) to stick to the figma design. I suggest decreasing the `margin-right` of your teck-stack `ul`   

**_Your_design:_**

<img width="262" alt="new ss" src="https://user-images.githubusercontent.com/44798044/219828280-be8359cd-a3ac-4836-bd62-691436ccf4ed.png">

**_Figma_design:_**

![ns](https://user-images.githubusercontent.com/44798044/219828292-f66ea4ab-b974-4e4c-8d4a-5093582ba0cc.png)

2023-02-18 03:26 UTC, shella12 commented on index.html
> +    <section id="about" class="about">
- [ ] As requested by the previous reviewer please make sure the `gap` between each `about-us` section elements looks identical to the the[ figma design template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=Dq0auABWvM0gt216-0)

**_Your design_**

<img width="364" alt="Screenshot 2023-02-18 at 7 21 03 AM" src="https://user-images.githubusercontent.com/44798044/219828526-5504fa96-c480-430a-9488-9f334f049ea6.png">

**_Figma design_**

<img width="529" alt="Screenshot 2023-02-18 at 8 06 07 AM" src="https://user-images.githubusercontent.com/44798044/219828595-3ec3fdd0-1c2a-4b0a-97f9-b2cff11c2193.png">

2023-02-18 03:26 UTC, shella12 commented on index.html
> +            <h1 class="about-me"> About Myself</h1>
- [ ] Please make sure the font-size of `about-us` heading looks like [figma design template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=Dq0auABWvM0gt216-0). I would also suggest putting a `<br>` break element between `about` and `myself` to make it look like figma design

**_Your design_**

<img width="282" alt="Screenshot 2023-02-18 at 7 21 09 AM" src="https://user-images.githubusercontent.com/44798044/219828708-17a09b96-9d7f-4b2e-b57c-4f3a332e18a0.png">

**_Figma design_**

<img width="286" alt="Screenshot 2023-02-18 at 8 10 23 AM" src="https://user-images.githubusercontent.com/44798044/219828703-bda3c428-6b8b-45bb-a23b-8a0ce1e91758.png">

2023-02-18 03:26 UTC, shella12 commented on index.html
> +                a project you need coded, don’t hestiate to contact me.
- [ ] Please make sure the `font-size` and `font-weight` of `intro1` paragraph looks like [figma design template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=Dq0auABWvM0gt216-0). 

**_Your design_**

<img width="317" alt="Screenshot 2023-02-18 at 7 21 13 AM" src="https://user-images.githubusercontent.com/44798044/219828750-7b3dc00a-0828-4c51-af80-ed5675063da0.png">

**_Figma design_**

<img width="494" alt="Screenshot 2023-02-18 at 8 13 13 AM" src="https://user-images.githubusercontent.com/44798044/219828788-0dedcf0e-524d-4aa8-bf1d-6879e45abd47.png">

2023-02-20 14:21 UTC, aamirkhan2478 requested changes
Hi @tGemechis7 , 

![](https://media4.giphy.com/media/CoND5j6Bn1QZUgm1xX/giphy.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Good Effort
✔️ Your design is good.
✔️ All linters checked
✔️ Descriptive PR summary

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-20 14:21 UTC, aamirkhan2478 commented on index.html
> +                          <a class="moresee-link btn-action-event">See project</a>
- [ ] Please make sure your button is exactly the same as the Frigma design and also use all button effects like hover, pressed etc. check below :point_down:  the difference: :+1: 

**Use these button effects:**
![Screenshot from 2023-02-19 00-56-06](https://user-images.githubusercontent.com/45226848/220127444-a3146d8d-8fd6-4844-9dcb-ed8ff3778d67.png)

**You Design:**
![Screenshot from 2023-02-20 18-26-28](https://user-images.githubusercontent.com/45226848/220127529-a18e439b-7bef-4e14-bafa-bfdaa34234c2.png)

**Figma Design:**
![Screenshot from 2023-02-20 18-26-15](https://user-images.githubusercontent.com/45226848/220127574-e0c00ceb-fdd2-412b-902f-8c30d6101c3b.png)

- [ ] Please give some border-radius in your `moresee-link` CSS class in the CSS file.  :slightly_smiling_face:

2023-02-20 14:21 UTC, aamirkhan2478 commented on index.html
> +    </ul>
- [ ] Please use the same Figma design as I mentioned above :point_up: your about section does not look like the Figma design check below :point_down: and kindly fix it :+1: 

**Your Design:**
![Screenshot from 2023-02-20 18-28-53](https://user-images.githubusercontent.com/45226848/220129156-7888c8b9-10cf-4b95-90dc-74dd4eaf9916.png)

**Figma Design**
![Screenshot from 2023-02-20 18-28-30](https://user-images.githubusercontent.com/45226848/220129268-af449d6b-00a3-46ec-8acb-70991d6945fb.png)

- [ ] Please use `width: 100%`  to the  `aboutmyself-section` class and also use `border-top-right-radius`  to the `aboutmyself-section` class in your CSS file.

2023-02-20 21:38 UTC, NahnahAJ requested changes
Hi @tGemechis7 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.
<img src="https://media2.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights
- [ ] No linter errors :heavy_check_mark: 
- [ ] Good use of GitHub flow :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-20 21:38 UTC, NahnahAJ commented on index.html
> +                    </div>
- [ ] Great job closing your tags as the previous reviewer asked. But it looks like after you made those changes, the previous margin/padding you had around your cards was removed and now they look quite different from the Figma template. So kindly add margin/padding to the containers so your work cards each look similar to the Figma design. :100: 
- [ ] Please ensure that you add equal spacing all around the cards so one side doesn't look bigger than the other like you had before :+1: 
- Your Design Now 
![image](https://user-images.githubusercontent.com/102699958/220200244-16267f0e-16de-40c5-a58f-ba8fd32f5963.png)

- The Figma Template
![image](https://user-images.githubusercontent.com/102699958/220200444-0585a4c9-e5bd-46a3-bcaf-08c1fdceb69f.png)

- Your Design Before
![image](https://user-images.githubusercontent.com/102699958/220200290-1ec6d8df-9cbe-4f4f-9813-72df41cadf17.png)

2023-02-20 21:38 UTC, NahnahAJ commented on index.html
> +                          <a class="moresee-link btn-action-event">See project</a>
- [ ] I noticed here that you still didn't make changes to the buttons as the previous reviewer suggested. Kindly include these requirements in your project as they are essential for user interaction. They can help provide clear visual feedback to the user when an action has been successfully completed, which helps to reduce user frustration and increase user satisfaction. :100:

2023-02-20 21:38 UTC, NahnahAJ commented on index.html
> +        </ul>
- [ ] It also looks like you made some changes that have changed the initial design you applied to these list items. Kindly re-add them so they look as they did previously :100: 
- Your Design Before
![image](https://user-images.githubusercontent.com/102699958/220201791-bd050d04-360d-46cc-b834-a94bdec09085.png)

- Your Design Now
![image](https://user-images.githubusercontent.com/102699958/220201809-417b277b-7ce6-460e-8b40-fb8c4b7cce70.png)

2023-02-21 09:44 UTC, wayungi requested changes
Hi @tGemechis7 , 
![image](https://user-images.githubusercontent.com/99656687/220082777-7a0e6a7f-854d-4e32-9c38-3b1eb3b090e4.png)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [ ] Profesional README ✔️ 
- [ ] All linter checks passing ✔️ 
- [ ] No merge conflicts ✔️ 
- [ ]  Correct GitHub flow ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 09:44 UTC, wayungi commented on index.html
> +            <div id="work-container">
- [ ] You have created another `div` inside the `<section class="grid-item grid-item-3 work-section">`. The main container of the projects is therefore  `<div id="work-container">` and should have a display:grid

2023-02-21 10:45 UTC, tGemechis7 commented
i don't undestand your comment can you please explain more

On Tue, Feb 21, 2023 at 12:44 PM Francis Wayungi ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @tGemechis7 <https://github.com/tGemechis7> ,
> [image: image]
> <https://user-images.githubusercontent.com/99656687/220082777-7a0e6a7f-854d-4e32-9c38-3b1eb3b090e4.png>
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet.
> Highlights
>
>    - Profesional README ✔️
>    - All linter checks passing ✔️
>    - No merge conflicts ✔️
>    - Correct GitHub flow ✔️
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/tGemechis7/Portfolio/pull/3#discussion_r1112810005>:
>
> > +         <section class="grid-item grid-item-3 work-section">
>
> +            <div id="work-container">
>
>
>
>    - You have created another div inside the <section class="grid-item
>    grid-item-3 work-section">. The main container of the projects is
>    therefore <div id="work-container"> and should have a display:grid
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tGemechis7/Portfolio/pull/3#pullrequestreview-1307054194>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4TCIVBL5VGLDGSJZBLYRBLWYSE7DANCNFSM6AAAAAAU73UPR4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-22 08:31 UTC, Shedrack-Sunday approved these changes
Hi @tGemechis7 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)


# Highlights
- No linter errors ✔️
- Good implementations ✔️

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-22 08:32 UTC, tGemechis7 commented
thank you ***@***.****

On Wed, Feb 22, 2023 at 11:31 AM Shedrack Sunday ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @tGemechis7 <https://github.com/tGemechis7>
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
> [image: image]
> <https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966>
> Highlights
>
>    - No linter errors ✔️
>    - Good implementations ✔️
>
> Optional suggestions
>
> Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have
> a limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tGemechis7/Portfolio/pull/3#pullrequestreview-1308743276>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4TCIVBKUDD2KRUJPEGEMTLWYXFGRANCNFSM6AAAAAAU73UPR4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-22 08:33 UTC, merged