Portflio desktop version
tGemechis7/Portfolio pull request #7
Opened 2023-03-03 21:22 UTC by tGemechis7

-I have added desktop version for my portfilio
-update index.html 
-update styleSheet.css for desktop version
-add some images w

2023-03-03 22:41 UTC, TuyishimireEric requested changes
# Status: REQUIRED CHANGES :recycle: 
### Hi  @tGemechis7   👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far 👍 
 there are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Highlights 👍 
✔ Descriptive PR ✨
✔ No linter Errors ✨

## Required Changes ♻️

- [ ]  check the comment below 👇 

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-03 22:41 UTC, TuyishimireEric commented on styleSheet.css
> +  padding-left: 200px;
- [ ] It is advised to always use dynamic **width**  like ```width: 100%;``` for your elements on the page instead of using fixed width, 😎😎
  Currently, you have an issue with your element's **width**, they are not fitting the web browser because their width is static, Kindly fix this to replicate the Figma design 😊😀

![image](https://user-images.githubusercontent.com/102757126/222838745-7fc4cc7c-9a78-44b2-8829-0240fcba88b2.png)

you may follow this[ link](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units) on CSS units
 _Dynamic width allows your website to be [responsive](https://www.w3schools.com/css/css_rwd_images.asp) and adapt to different screen sizes and devices. This is increasingly important in today's world where users are accessing websites on a wide range of devices, from desktop computers to smartphones and tablets. 👍 _

2023-03-03 22:41 UTC, TuyishimireEric commented on styleSheet.css
> +}
- [ ] I think it would be better to replicate the [Figma template design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=34%3A848&t=vWwm5FL2DCLCGdGS-0) by adjusting the **font-size** of your title to match the given Figma design as much as possible 🙏 

**Currently**
![image](https://user-images.githubusercontent.com/102757126/222840100-203083a9-9437-4f51-a964-8bd9553d398b.png)

**Figma design**
![image](https://user-images.githubusercontent.com/102757126/222840163-6c272070-26e1-41fd-b597-2ed3fc646b2e.png)

2023-03-03 22:41 UTC, TuyishimireEric commented on index.html
> +              </li>
- [ ] I think it would be better to adjust the spaces between your elements in each project ***(margin and padding)*** to replicate the figma design as much as possible, 🙏
- [ ]  It would be better also to align the button to your project card to the left of the second part as given on the original design 😁😁😁

 I have highlighted some areas to be fixed for your reference 👇  
![image](https://user-images.githubusercontent.com/102757126/222842263-ab267a01-062e-49d4-ab02-b8b29ff5094c.png)

**FIgma design**
![image](https://user-images.githubusercontent.com/102757126/222842620-0a771b35-4f7a-4d83-b003-05a850c669fd.png)

--- 
## Mobile version 📴 

- [ ] I have noticed that the design on your mobile version differs from that of the Figma design, Kindly make sure that your mobile version replicates the Figma design as much as possible 🙏 
   - Mostly on the Contact section of the mobile version, it has changed the original design, you may try to replicate the Figma design on every section 😁😁

    - you may try to avoid scrolling horizontally on your page for the Best user experience and to make your site more professional 👍 
    example: you may try to add in the CSS of ```body { overflow: hidden;}```
 
- [ ] Currently, the Font-size of all your mobile content are small they can not be readable, 😨 😨 Kindly try to make these adjustments 🙏 

https://www.loom.com/share/7c489633012b48dfba5157dad21665b0

2023-03-04 01:38 UTC, didierganthier requested changes
Hi @tGemechis7  ,

🎉 Great job on addressing the feedback from the previous review! You've made some solid progress in implementing the requested changes. However, there are still a few areas that need some attention before we can move on to the next project.

<img src="https://media.giphy.com/media/L422JoNlBBBD42zkQ9/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct GitHub flow ✔️ 

## Required Changes 🛠
- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-03-04 01:38 UTC, didierganthier commented on styleSheet.css
> +  padding-left: 200px;
Well done on making some of the changes requested 🎉 but the `width` issue still hasn't been addressed, your `body` has a `width` of `1440px` wich means that it'll be fixed to that `width` and won't adapt to screen resizes, kindly take a look at the previous reviewer's recommendation on how to fix this. 🤓

2023-03-04 01:38 UTC, didierganthier commented on index.html
> +              </li>
Nice work fixing the `button` alignment issue as it was very important to improve your design 🎨 but there are still certain things to handle:
- [ ] The overflow issue ⛲ results in a very bad `UX` because the user has to scroll horizontally to see some of the contents, look to fix that with `body { overflow: hidden;}` as suggested by the previous reviewer 🤔 , if that was not to work you could look more into overflow [here](https://www.w3schools.com/css/css_overflow.asp)
- [ ] Look to adjust the font-size as well as requested by the previous reviewer 👍🏽

2023-03-04 01:38 UTC, didierganthier commented on index.html
> +          </form>
Caught ya 😉 you have a closing `form` tag here that doesn't correspond to any opening ones, look to remove that as it makes your HTML structure incorrect. ❌

2023-03-04 01:38 UTC, didierganthier commented on index.html
> +              <input type="submit" class="btn-more" value="Get in touch" name="buttonsubmit">
Hey 👋🏽 seems like you centered the contact form 🎊 but you also added some border to the button container that was not part of the original design 🎨 look to remove that as it does not fit the rest. 😉 
![Screenshot 2023-03-03 at 20 36 20](https://user-images.githubusercontent.com/45739963/222868648-125d3aa2-04ad-4315-a7f5-0f5a39ca15e5.png)

2023-03-04 18:37 UTC, huseyinbiyik requested changes
Hi @tGemechis7,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![tenor](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif)

 ## Highlights
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- .gitignore used to ignore requested files 📁
- PR description is descriptive 📝


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
-  Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example, 
👌"Add logo to navigation bar"
👌"Fix close button functionality on mobile navbar"
❌ "Added logo to navigation bar"
❌ "Added HTML"
- Kindly fix the empty spaces around Header, Heading, About Me, Contacts section.
<img width="1434" alt="Screenshot 2023-03-04 at 9 25 54 PM" src="https://user-images.githubusercontent.com/25887253/222923021-3de09728-4605-4674-af16-57861b84a28f.png">
- Please remove the templated text from your README file to have a customized and professional repository.
<img width="1074" alt="Screenshot 2023-03-04 at 9 31 55 PM" src="https://user-images.githubusercontent.com/25887253/222923090-3ac09608-54c4-4216-9e69-fdcface8dfbe.png">
<img width="1074" alt="Screenshot 2023-03-04 at 9 32 02 PM" src="https://user-images.githubusercontent.com/25887253/222923092-82b17a7c-be22-4cf7-86dc-f041811c325d.png">
<img width="1074" alt="Screenshot 2023-03-04 at 9 32 06 PM" src="https://user-images.githubusercontent.com/25887253/222923093-f67c3e74-d4c3-4084-ab0e-ce8b0e8c0825.png">


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-04 18:37 UTC, huseyinbiyik commented on index.html
> +          <h1 class="fsw-7">I’m Gemechis <br>Glad to see you!</h1>
As the previous reviewers requested, please fix the font-size of the heading element like on the Figma template.
<img width="623" alt="Screenshot 2023-03-04 at 9 30 14 PM" src="https://user-images.githubusercontent.com/25887253/222922943-fafe34a1-36b0-4092-841b-622d61cbd929.png">
<img width="784" alt="Screenshot 2023-03-04 at 9 30 41 PM" src="https://user-images.githubusercontent.com/25887253/222922946-576b25c5-f148-4c6b-ac7c-73b585c10e04.png">

2023-03-04 19:40 UTC, Nemwel-Boniface reviewed
## Hello @tGemechis7  👋,

I am Nemwel your reviewer.


## _This is an additional review as a result of the second opinion request._

I have inspected the last reviews given in your pull request and the review given by @huseyinbiyik was not consistent with the previous reviewer (@didierganthier ). The requested changes by @huseyinbiyik should have been marked as optional.

Because the requested changes are optional, I think your project can be approved.

**Note** However, I highly suggest that you should implement.the following:

- [ ] Your project seems to be having a margin/ padding left and right which makes your project to have a white space at its ends. This is not the desired design and it would be a good thing to fix it to make your portfolio stellar :stars: 
![image](https://user-images.githubusercontent.com/86318284/222925453-c326b58d-79c0-41d8-8867-ba47f1cbecc1.png)


As this was the only reason that your project was not approved, kindly submit it in your dashboard and the next reviewer will approve it immediately :rocket: 

In case anything is not 100% clear tag me @Nemwel-Boniface so that I get the notification.

Keep rocking 🚀!

2023-03-04 19:42 UTC, Nemwel-Boniface commented
@tGemechis7 Kindly note that when you fill a second opinion request form, you are not required to push any code/ request any reviews until the second opinion has been completed otherwise the result of the second opinion might change.

2023-03-04 20:41 UTC, zieeco approved these changes
# status: APPROVED :green_circle: :100: 

Hi, @tGemechis7 , 


![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)


Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡ 

✅ Descriptive PR 👍 
✅ Nice design 🔥 
✅ Linters are passing 👏 


## Optional suggestions
- N/A


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-04 20:41 UTC, merged